// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI-only connection (migrate/seed). Prefer Neon's direct/unpooled
    // connection here — Prisma Migrate's advisory-lock + DDL operations
    // are unreliable over a transaction-mode pooler (Neon's default).
    // Falls back to DATABASE_URL so a single-URL local setup still works.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
